FROM python:3.11.3
WORKDIR /code
RUN apt-get update
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN apt-get install vim -y
COPY ./app /code/app
COPY . /code/
EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
